create table customer (
    id bigint generated by default as identity,
    name varchar(255) not null,
    date_of_birth date,
    cpf varchar(255) not null,
    email varchar(255) not null,
    created_by varchar(255),
    created_at timestamp(6),
    updated_by varchar(255),
    updated_at timestamp(6),
    primary key (id)
);

create table reservation (
    id bigint generated by default as identity,
    code varchar(255) not null,
    customer_id bigint,
    reserved_room_id bigint,
    reservation_price float(53) not null,
    description varchar(255) not null,
    duration integer not null,
    start_date date not null,
    end_date date not null,
    active boolean not null,
    created_by varchar(255),
    created_at timestamp(6),
    updated_by varchar(255),
    updated_at timestamp(6),
    primary key (id)
);

create table room (
    id bigint generated by default as identity,
    number integer not null,
    description varchar(255) not null,
    size float(53) not null,
    busy boolean not null,
    active boolean not null,
    price_per_month float(53) not null,
    created_by varchar(255),
    created_at timestamp(6),
    updated_by varchar(255),
    updated_at timestamp(6),
    primary key (id)
);